// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.client.testapp;


public abstract class HelloPrxCallback {

	public abstract void callback_hello(String ret);

}
