// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.client.testapp;

import com.qq.tars.protocol.annotation.Servant;
import com.qq.tars.protocol.tars.annotation.TarsContext;

import java.util.concurrent.CompletableFuture;

@Servant
public interface HelloPrx {

    String hello(int no, String name);

    CompletableFuture<String> promise_hello(int no, String name);

    String hello(int no, String name, @TarsContext java.util.Map<String, String> ctx);
}
