// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars;

public enum DateType {

	SECONDS(0),
	MINIUES(1),
	HOUR(2),
	DAY(3),
	MONTH(4),
	YEAR(5);

	private final int value;

	private DateType(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static DateType convert(int value) {
		for(DateType v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
