// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.support.query.prx;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

/**
 * Get the query interface of the object endpoint
 */
public abstract class QueryFPrxCallback extends TarsAbstractCallback {

	public abstract void callback_findObjectById(java.util.List<EndpointF> ret);

	public abstract void callback_findObjectById4Any(int ret, java.util.List<EndpointF> activeEp, java.util.List<EndpointF> inactiveEp);

	public abstract void callback_findObjectById4All(int ret, java.util.List<EndpointF> activeEp, java.util.List<EndpointF> inactiveEp);

	public abstract void callback_findObjectByIdInSameGroup(int ret, java.util.List<EndpointF> activeEp, java.util.List<EndpointF> inactiveEp);

	public abstract void callback_findObjectByIdInSameStation(int ret, java.util.List<EndpointF> activeEp, java.util.List<EndpointF> inactiveEp);

	public abstract void callback_findObjectByIdInSameSet(int ret, java.util.List<EndpointF> activeEp, java.util.List<EndpointF> inactiveEp);

	public abstract void callback_findSubsetConfigById(int ret, com.qq.tars.client.subset.SubsetConf conf);

}
