// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.netty;

import com.qq.tars.common.support.Holder;
import com.qq.tars.protocol.annotation.Servant;
import com.qq.tars.protocol.tars.annotation.TarsHolder;
import com.qq.tars.protocol.tars.annotation.TarsMethodParameter;

@Servant
public interface MonitorQueryServant {

    int query(@TarsMethodParameter(name = "req") MonitorQueryReq req, @TarsHolder(name = "rsp") Holder<MonitorQueryRsp> rsp);
}
